package main

import (
	"log"
	"os"
	"text/template"
	"time"
)

func main() {

	var footballClubs = []string{
		"Manchester United",
		"Liverpool",
		"Arsenal",
		"Chelsea",
		"Manchester City",
		"Tottenham Hotspur",
		"Everton",
		"Southamptun",
		"Brighton Albion",
	}

	f, err := os.Create("../premierleague/footballclub.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Clubs     []string
	}{
		Timestamp: time.Now(),
		Clubs:     footballClubs,
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package premierleague

var FootballClubs = []string{
{{- range .Clubs }}
	{{ printf "%q" . }},
{{- end }}
}
`))